### ISSUE TITLE
User log out when navigate other screen

### ISSUE THREAD

**Issue by mustafayildiz12** [ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter#1]
![image](https://user-images.githubusercontent.com/69385336/209799101-bc0a367e-8a8c-47ba-b0f3-5122c41b5dc4.png)
![WhatsApp Image 2022-12-28 at 13 36 57](https://user-images.githubusercontent.com/69385336/209799232-9be9bd0b-c0d5-4d35-9d20-42decd59de2e.jpeg)
![image](https://user-images.githubusercontent.com/69385336/209799310-a65c12a5-ef96-42bb-a1ad-dff7e395c055.png)
![image](https://user-images.githubusercontent.com/69385336/209799391-f2ceb790-8370-4fc4-a716-f46af39eff71.png)
![image](https://user-images.githubusercontent.com/69385336/209799419-f7f3de79-17dc-4117-af28-d6205ce9c006.png)

Hi.Iam using  zego_uikit_prebuilt_call: ^1.2.1 and zego_uikit_signaling_plugin: ^1.1.0. Actually the calling system is working well voice ,video and group call.But the users have to bee same page which includes ZegoUIKitPrebuiltCallWithInvitation widget.When I try to navigate back or another screen.The console says that the user is logged of.But I want to call other user even the app is closed.How to do that.Thanks.

**Comment by mustafayildiz12** [comment]
![image](https://user-images.githubusercontent.com/69385336/209801568-8a9f816e-4462-407b-a499-a451956cedb6.png)
![image](https://user-images.githubusercontent.com/69385336/209801644-30e06a6b-62d8-4020-a6a6-575ec4d50a4b.png)
![image](https://user-images.githubusercontent.com/69385336/209801788-53f62db1-e935-48e4-9ec3-7446fc3ebd3c.png)

I tried zego_zim: ^2.5.0+1 package to login zego.The state and event changed and login succees.Then I navigate my call screen which incluedes  ZegoUIKitPrebuiltCallWithInvitation widget.After navigate other screen, it throws null error.How to solve that.

**Comment by gitmuyang** [comment]
> ![image](https://user-images.githubusercontent.com/69385336/209799101-bc0a367e-8a8c-47ba-b0f3-5122c41b5dc4.png) ![WhatsApp Image 2022-12-28 at 13 36 57](https://user-images.githubusercontent.com/69385336/209799232-9be9bd0b-c0d5-4d35-9d20-42decd59de2e.jpeg) ![image](https://user-images.githubusercontent.com/69385336/209799310-a65c12a5-ef96-42bb-a1ad-dff7e395c055.png) ![image](https://user-images.githubusercontent.com/69385336/209799391-f2ceb790-8370-4fc4-a716-f46af39eff71.png) ![image](https://user-images.githubusercontent.com/69385336/209799419-f7f3de79-17dc-4117-af28-d6205ce9c006.png)
> 
> Hi.Iam using zego_uikit_prebuilt_call: ^1.2.1 and zego_uikit_signaling_plugin: ^1.1.0. Actually the calling system is working well voice ,video and group call.But the users have to bee same page which includes ZegoUIKitPrebuiltCallWithInvitation widget.When I try to navigate back or another screen.The console says that the user is logged of.But I want to call other user even the app is closed.How to do that.Thanks.

You only can join one call at the same time. In addition, when you exit the call page, the user will exit the call, if you want to join the other call, you need to restart the call.

**Comment by mustafayildiz12** [comment]
Thank you for answering.Appreciate it. Windows için Posta ile gönderildi Kimden: muyangGönderilme: 28 Aralık 2022 Çarşamba 18:14Kime: ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutterBilgi: mustafa Yıldız; AuthorKonu: Re: [ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter] User log out when navigate other screen (Issue #1) Hi.Iam using zego_uikit_prebuilt_call: ^1.2.1 and zego_uikit_signaling_plugin: ^1.1.0. Actually the calling system is working well voice ,video and group call.But the users have to bee same page which includes ZegoUIKitPrebuiltCallWithInvitation widget.When I try to navigate back or another screen.The console says that the user is logged of.But I want to call other user even the app is closed.How to do that.Thanks.You only can join one call at the same time. In addition, when you exit the call page, the user will exit the call, if you want to join the other call, you need to restart the call.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
