### ISSUE TITLE
How to join an ongoing video call?

### ISSUE THREAD

**Issue by AliEmx** [ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter#2]
How to join an ongoing video call?

**Comment by yoer** [comment]
you can join by same call id

https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter/tree/master/group_call

**Comment by AliEmx** [comment]
I am using ZegoSendCallInvitationButton for a group video call with multiple invitees and there is no option to add a call id.

**Comment by yoer** [comment]
[ZegoSendCallInvitationButton](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter/blob/master/invitation_call/lib/main.dart) is use to invite someone, call id will generate inside, 
```dart

class ZegoSendCallInvitationButton extends StatefulWidget {
  const ZegoSendCallInvitationButton({
    Key? key,
    required this.invitees,
    required this.isVideoCall,
  }) : super(key: key);

  /// here is a invite array, if you want to invite more than one
  final List<ZegoUIKitUser> invitees;
  final bool isVideoCall;
```

[ZegoUIKitPrebuiltCall](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter/blob/master/group_call/lib/main.dart) can custom call id by yourself, just like this
```dart

class ZegoUIKitPrebuiltCall extends StatefulWidget {
  const ZegoUIKitPrebuiltCall({
    Key? key,
    required this.callID,
  }) : super(key: key);

  /// You can customize the callID arbitrarily,
  /// just need to know: users who use the same callID can talk with each other.
  final String callID;
```
