### ISSUE TITLE
Some issues with offline invitations

### ISSUE THREAD

**Issue by iveshzf** [ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter#4]
I followed the procedure on the official website to operate call_with_offline_invitation, but after killing the program in the background, I did not receive the offline invitation.

**Comment by iveshzf** [comment]
Your troubleshooting documentation mentions notifyWhenAppRunningInBackgroundOrQuit, but I can't find its use anywhere.

**Comment by iveshzf** [comment]
I have found the problem. Since the mobile phone manufacturer has split some permissions, I must turn on all relevant permissions to receive notifications. But I hope you can learn more about this and update the documentation. This does cause a lot of problems for newbies like me

**Comment by yoer** [comment]
what do u mean **all relevant permissions to receive notifications**? Can you be more specific? A more detailed expression would better help others..

**Comment by iveshzf** [comment]
Just like the example using Xiaomi in your document, I don't know exactly what permissions my phone requires because I have turned on all the permissions I can see. My immediate hope is that you will add suggestions for users to check app permissions at https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Troubleshooting%20call%20invitations/4981e46f#h-1-caller-clicks- call-button-but-callee-does-not-receive-call-invitation-notification-when-offline

**Comment by iveshzf** [comment]
Your configuration tutorial for offline push is already detailed enough. In comparison, issues related to permissions are easily overlooked. I don't want more careless people like me to be troubled by this problem.

**Comment by yoer** [comment]
now we support [Troubleshooting call invitations](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Troubleshooting%20call%20invitations/4981e46f)
