### ISSUE TITLE
How to check for another user that is busy or not in one to one voice call . Is there any event function or plugin

### ISSUE THREAD

**Issue by jitendravn** [ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter#5]

**Comment by kaleem-code** [comment]
how to check if user is on another call?

**Comment by yoer** [comment]
plz create issue in [here](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues)

**Comment by kaleem-code** [comment]
> plz create issue in [here](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues)

i'm not creating an issue just asking for the existing issue.

**Comment by yoer** [comment]
There is no such API currently provided

When a call is in progress, if a call comes in at this time, the call will be automatically rejected.

If you need to know the call status of your users, you can maintain the call status yourself based on these [event](https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/topics/Events-topic.html)
